### ISSUE TITLE
User profile → Reputation score → See more → HTTP 500

### ISSUE THREAD

**Issue by mgomezch** [mgomezch/mahisoft-km#1]
Example: https://km.mahisoft.com/users/1002/manuel-gomez/reputation

Log:

```
mamute_1   | URL: /users/1002/manuel-gomez/reputation
mamute_1   | Headers:
mamute_1   |     Upgrade-Insecure-Requests: 1
mamute_1   |     Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
mamute_1   |     Connection: close
mamute_1   |     X-Forwarded-Proto: https
mamute_1   |     DNT: 1
mamute_1   |     Referer: https://km.mahisoft.com/users/1002/manuel-gomez
mamute_1   |     Accept-Encoding: gzip, deflate, sdch, br
mamute_1   |     User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
mamute_1   |     Accept-Language: en-US,en;q=0.8,es;q=0.6
mamute_1   |     X-Forwarded-For: 190.39.2.40
mamute_1   |     Cookie: __unam=710b07c-156991c64f6-5861f6ab-23; brutal_session=a3be781fa075be0871dea21cca10b0544f13cc730cfde536d0e0ec58bb3a60c3; JSESSIONBRUTAL=19eu6co6vttkj14uqt6xqwdbgo
mamute_1   |     Host: km.mahisoft.com
mamute_1   | User-id : [user = [User mgomez@mahisoft.com, Manuel Gómez, 1002], ip = 172.18.0.4]
mamute_1   | Exception: 
mamute_1   | org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [org.mamute.model.Question#2]
mamute_1   | 	at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:244)
mamute_1   | 	at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:261)
mamute_1   | 	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:175)
mamute_1   | 	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:285)
mamute_1   | 	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)
mamute_1   | 	at org.mamute.model.Question_$$_jvst3df_10.isVisible(Question_$$_jvst3df_10.java)
mamute_1   | 	at org.mamute.dto.KarmaByContextHistory.<init>(KarmaByContextHistory.java:19)
mamute_1   | 	at org.mamute.dao.ReputationEventDAO.karmaWonByQuestion(ReputationEventDAO.java:116)
mamute_1   | 	at org.mamute.controllers.UserProfileController.reputationHistory(UserProfileController.java:91)
mamute_1   | 	at org.mamute.controllers.UserProfileController$Proxy$_$$_WeldClientProxy.reputationHistory(Unknown Source)
mamute_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mamute_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
mamute_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mamute_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
mamute_1   | 	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:38)
mamute_1   | 	at net.vidageek.mirror.invoke.MethodHandlerByMethod.withArgs(MethodHandlerByMethod.java:54)
mamute_1   | 	at br.com.caelum.vraptor.observer.ExecuteMethod.execute(ExecuteMethod.java:87)
mamute_1   | 	at br.com.caelum.vraptor.actioncache.events.CachedExecuteMethod.access$001(CachedExecuteMethod.java:24)
mamute_1   | 	at br.com.caelum.vraptor.actioncache.events.CachedExecuteMethod$1.run(CachedExecuteMethod.java:44)
mamute_1   | 	at br.com.caelum.vraptor.actioncache.events.ExecuteIfNoCache.execute(ExecuteIfNoCache.java:32)
mamute_1   | 	at br.com.caelum.vraptor.actioncache.events.CachedExecuteMethod.execute(CachedExecuteMethod.java:41)
mamute_1   | 	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
mamute_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mamute_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
mamute_1   | 	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
mamute_1   | 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
mamute_1   | 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
mamute_1   | 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
mamute_1   | 	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
mamute_1   | 	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:170)
mamute_1   | 	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:124)
mamute_1   | 	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:84)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:78)
mamute_1   | 	at org.mamute.providers.GlobalInterceptor.intercept(GlobalInterceptor.java:28)
mamute_1   | 	at org.mamute.providers.GlobalInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at org.mamute.interceptors.InternalErrorInterceptor.intercept(InternalErrorInterceptor.java:37)
mamute_1   | 	at org.mamute.interceptors.InternalErrorInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at org.mamute.interceptors.RulesInterceptor.intercept(RulesInterceptor.java:49)
mamute_1   | 	at org.mamute.interceptors.RulesInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.brutauth.interceptors.BrutauthRuleInterceptor.intercept(BrutauthRuleInterceptor.java:40)
mamute_1   | 	at br.com.caelum.brutauth.interceptors.BrutauthRuleInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at org.mamute.interceptors.RedirectCommitInterceptor.intercept(RedirectCommitInterceptor.java:39)
mamute_1   | 	at org.mamute.interceptors.RedirectCommitInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor.intercept(ExceptionHandlerInterceptor.java:75)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.ExceptionHandlerInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$$_WeldClientProxy.next(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack.next(DefaultSimpleInterceptorStack.java:49)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack$Proxy$_$$_WeldClientProxy.next(Unknown Source)
mamute_1   | 	at org.mamute.providers.TransactionInterceptor.intercept(TransactionInterceptor.java:42)
mamute_1   | 	at org.mamute.providers.TransactionInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
mamute_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mamute_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
mamute_1   | 	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:38)
mamute_1   | 	at net.vidageek.mirror.invoke.MethodHandlerByMethod.withArgs(MethodHandlerByMethod.java:54)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.StepInvoker.invokeMethod(StepInvoker.java:49)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.StepInvoker.tryToInvoke(StepInvoker.java:40)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.StepInvoker$Proxy$_$$_WeldClientProxy.tryToInvoke(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor.executeAround(InterceptorExecutor.java:75)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor$Proxy$_$$_WeldClientProxy.executeAround(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.AspectStyleInterceptorHandler.execute(AspectStyleInterceptorHandler.java:85)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$$_WeldClientProxy.next(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack.next(DefaultSimpleInterceptorStack.java:49)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.DefaultSimpleInterceptorStack$Proxy$_$$_WeldClientProxy.next(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.simplemail.AsyncMailerFlushInterceptor.intercept(AsyncMailerFlushInterceptor.java:33)
mamute_1   | 	at br.com.caelum.vraptor.simplemail.AsyncMailerFlushInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
mamute_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mamute_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
mamute_1   | 	at net.vidageek.mirror.provider.java.PureJavaMethodReflectionProvider.invoke(PureJavaMethodReflectionProvider.java:38)
mamute_1   | 	at net.vidageek.mirror.invoke.MethodHandlerByMethod.withArgs(MethodHandlerByMethod.java:54)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.StepInvoker.invokeMethod(StepInvoker.java:49)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.StepInvoker.tryToInvoke(StepInvoker.java:40)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.StepInvoker$Proxy$_$$_WeldClientProxy.tryToInvoke(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor.executeAround(InterceptorExecutor.java:75)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.InterceptorExecutor$Proxy$_$$_WeldClientProxy.executeAround(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.AspectStyleInterceptorHandler.execute(AspectStyleInterceptorHandler.java:85)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at org.mamute.interceptors.PimpMyControllerInterceptor.intercept(PimpMyControllerInterceptor.java:31)
mamute_1   | 	at org.mamute.interceptors.PimpMyControllerInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at org.mamute.interceptors.BlockedIpInterceptor.intercept(BlockedIpInterceptor.java:44)
mamute_1   | 	at org.mamute.interceptors.BlockedIpInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.brutauth.interceptors.BrutauthMapInterceptor.intercept(BrutauthMapInterceptor.java:36)
mamute_1   | 	at br.com.caelum.brutauth.interceptors.BrutauthMapInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.AspectStyleInterceptorHandler.execute(AspectStyleInterceptorHandler.java:88)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.FlashInterceptor.intercept(FlashInterceptor.java:98)
mamute_1   | 	at br.com.caelum.vraptor.interceptor.FlashInterceptor$Proxy$_$$_WeldClientProxy.intercept(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.core.ToInstantiateInterceptorHandler.execute(ToInstantiateInterceptorHandler.java:58)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.next(DefaultInterceptorStack.java:83)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack.start(DefaultInterceptorStack.java:93)
mamute_1   | 	at br.com.caelum.vraptor.core.DefaultInterceptorStack$Proxy$_$$_WeldClientProxy.start(Unknown Source)
mamute_1   | 	at br.com.caelum.vraptor.observer.RequestHandlerObserver.handle(RequestHandlerObserver.java:93)
mamute_1   | 	at org.mamute.infra.locale.CustomRequestHandlerObserver.handle(CustomRequestHandlerObserver.java:42)
mamute_1   | 	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
mamute_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mamute_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
mamute_1   | 	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
mamute_1   | 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
mamute_1   | 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
mamute_1   | 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
mamute_1   | 	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
mamute_1   | 	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:170)
mamute_1   | 	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:124)
mamute_1   | 	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:84)
mamute_1   | 	at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:123)
mamute_1   | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1336)
mamute_1   | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:483)
mamute_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
mamute_1   | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:521)
mamute_1   | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
mamute_1   | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
mamute_1   | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
mamute_1   | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
mamute_1   | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
mamute_1   | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
mamute_1   | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
mamute_1   | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
mamute_1   | 	at org.eclipse.jetty.server.Server.handle(Server.java:351)
mamute_1   | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451)
mamute_1   | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:916)
mamute_1   | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
mamute_1   | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
mamute_1   | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
mamute_1   | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
mamute_1   | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
mamute_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
mamute_1   | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
mamute_1   | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mgomezch** [comment]
Fixed in https://github.com/mgomezch/mamute/commit/7740eb9b9a7336e0155aad6da428d02e9d2ffe8a
